name: nearby_buddy_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+9


environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences:
  font_awesome_flutter:
  flutter_svg:
  currency_text_input_formatter:
  google_maps_flutter:
  location:
  geocoding:
  image_picker: ^0.8.4+4
  lottie:
  flutter_polyline_points: ^1.0.0
  flutter_swiper_null_safety: ^1.0.2
  google_sign_in: ^5.0.3
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.2
  intl: ^0.17.0
  firebase_analytics:
  google_maps_flutter_web:
  pointer_interceptor:
  pin_code_fields: ^7.3.0
  cached_network_image:
  dotted_border:
  file_picker: ^3.0.0
  flutter_ringtone_player: ^3.2.0
  photo_view: ^0.14.0
  shimmer:
  image_cropper:
  slide_action: ^0.0.2
  toggle_switch: ^2.1.0
  change_app_package_name: ^1.1.0
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  observable: ^0.24.0
  carousel_slider: 4.2.1
  app_settings: ^4.2.0
  flutter_local_notifications: ^14.1.1
  js:
  syncfusion_flutter_datepicker:
  geolocator: ^8.0.1
  url_launcher: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_address_from_latlng: ^0.0.2
  side_navigation: ^1.0.4
  provider: ^6.1.1
  flutter_showcaseview: ^2.1.3
  tutorial_coach_mark: ^1.2.11
  pointer_interceptor_web: ^0.10.0
  path: ^1.9.0
  flutter_hooks: ^0.20.5
  flutter_emoji: ^2.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  flutter_launcher_icons: ^0.10.0
  flutter_facebook_auth:
  package_info_plus: ^3.0.3
  crypto: ^3.0.1
  custom_marker: ^1.0.0
  flutter_speed_dial: ^5.0.0+1
  firebase_messaging:
  firebase_crashlytics: ^3.4.18
  device_info:
  overlay_support:
  cloud_firestore:
  conditional_builder_null_safety: ^0.0.6
  equatable:

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/buddy_logo.png"
    background_color: "#8341AF"
    theme_color: "#8341AF"
  image_path: "assets/images/buddy_logo.png"
  adaptive_icon_foregound: "assets/images/buddy_logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/strings/mapStyles.txt
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 200
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Light.ttf
          weight: 200

