// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpWFPYucj9z7EkNnDAdb-n5EHky55Gzz0',
    appId: '1:729641081086:web:6f71044aa8640651676daf',
    messagingSenderId: '729641081086',
    projectId: 'nearbybuddy-beca4',
    authDomain: 'nearbybuddy-beca4.firebaseapp.com',
    storageBucket: 'nearbybuddy-beca4.appspot.com',
    measurementId: 'G-HR4F6P4XCG',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWFPYucj9z7EkNnDAdb-n5EHky55Gzz0',
    appId: '1:729641081086:web:6f71044aa8640651676daf',
    messagingSenderId: '729641081086',
    projectId: 'nearbybuddy-beca4',
    authDomain: 'nearbybuddy-beca4.firebaseapp.com',
    storageBucket: 'nearbybuddy-beca4.appspot.com',
    measurementId: 'G-HR4F6P4XCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl46UrFziNgcMcUsAuREtRBA2h4z9yMtA',
    appId: '1:729641081086:android:764da02bfec1d967676daf',
    messagingSenderId: '729641081086',
    projectId: 'nearbybuddy-beca4',
    storageBucket: 'nearbybuddy-beca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Zbo1nJDTYrZceMXtibELmHn_4wDviI8',
    appId: '1:729641081086:ios:723459cc9e96d6ef676daf',
    messagingSenderId: '729641081086',
    projectId: 'nearbybuddy-beca4',
    storageBucket: 'nearbybuddy-beca4.appspot.com',
    iosClientId: '729641081086-7ie78rl2ls7ukk1eei4b4liverljcorq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbyBuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Zbo1nJDTYrZceMXtibELmHn_4wDviI8',
    appId: '1:729641081086:ios:723459cc9e96d6ef676daf',
    messagingSenderId: '729641081086',
    projectId: 'nearbybuddy-beca4',
    storageBucket: 'nearbybuddy-beca4.appspot.com',
    iosClientId: '729641081086-7ie78rl2ls7ukk1eei4b4liverljcorq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbyBuddyApp',
  );
}
